In [3]:
import numpy as np # numpy -> Numerical Python, np - alias

x = [2, 5, 5]
y = [9, 4, 2]
print(x + y)
x_np = np.array(x) # numpy array, массив numpy, вектор
y_np = np.array(y)
print(type(x_np)) # nd - n-dimensional
print(x_np)

[2, 5, 5, 9, 4, 2]
<class 'numpy.ndarray'>
[2 5 5]


In [9]:
print(x_np + y_np)
print(x_np * y_np)
print(np.log(x_np))

[11  9  7]
[18 20 10]
[0.69314718 1.60943791 1.60943791]


In [10]:
np.array([0.62, 0.72]) * 100

array([62., 72.])

In [12]:
A = [[3, 5, 1], [5, 10, 4], [4, 20, 4]]
A[1][0]

5

In [13]:
A_np = np.array(A)
print(A_np)

[[ 3  5  1]
 [ 5 10  4]
 [ 4 20  4]]


In [21]:
print(A_np[0][1])
print(A_np[0, 1])
print(A_np[1, :])
print(A_np[:, 2])
print(A_np[:2, 2])

5
5
[ 5 10  4]
[1 4 4]
[1 4]


In [31]:
example = [False, True]
print(example)
example_np = np.array(example)
print(example_np) # гомогенность - может хранить только один тип данных

[False, True]
[False  True]


In [37]:
x_np.std()

1.4142135623730951

In [39]:
print(A_np)

[[ 3  5  1]
 [ 5 10  4]
 [ 4 20  4]]


In [43]:
print(A_np.mean()) # среднее для всей матрицы
print(A_np.min(axis=0)) # среднее по колонкам
print(A_np.min(axis=1)) # среднее по рядам

6.222222222222222
[3 5 1]
[1 4 4]


In [44]:
np.median(x_np)

5.0

In [48]:
A_np.size

9

In [49]:
ages = np.array([[15, 23, 32, 45, 52], 
               [68, 34, 55, 78, 20], 
               [25, 67, 33, 45, 14]])

In [55]:
~((ages >= 18) & (ages <= 65)) # and = &, not = ~

array([[ True, False, False, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True]])

In [54]:
(ages < 18) | (ages > 65) # or = |

array([[ True, False, False, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True]])

In [56]:
ages[(ages < 18) | (ages > 65)] # boolean mask, маскирование, булевая маска

array([15, 68, 78, 67, 14])

In [58]:
x_np[[True, True, False]]

array([2, 5])

In [60]:
(ages < 18) & (ages > 65)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [61]:
ages[(ages < 18) & (ages > 65)]

array([], dtype=int64)